### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-1-mapa-mental-FedericoVictorianoSierra#1]

**Comment by FedericoVictorianoSierra** [comment]
[Elicitación de requisitos (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-FedericoVictorianoSierra/files/10609112/Elicitacion.de.requisitos.Federico.Victoriano.Sierra.pdf)

**Comment by mel-16** [comment]
20% MUY BIEN

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
